### ISSUE TITLE
Optimize for database index use case

### ISSUE THREAD

**Issue by alicia-lyu** [frozenca/BTree#12]
Hi, I just want this community to know that I am adapting this repository to optimize for database index use. 

In the database world, it is almost always the case that only separator keys are stored in internal nodes, the data itself is stored separately, i.e., not directly mapped to keys as values. The rationale is that separator keys (or guiding keys) should in most cases fit into memory, even when the dataset is as large as a few TBs. See Graefe Modern B-Tree Techniques, chap. 2.1.

The data itself is stored in pages (e.g. 4KB), i.e. units that are optimized for disk IO (buffered read and write). It also allows partial access, as we cannot deserialize a few TB all at once. The data pages will support container operations with the order of magnitude of binary search.

The repository is [here](https://github.com/alicia-lyu/BTree). It is still under development. Advice is appreciated. However, as this is part of a larger project, for which I am under deadlines, cooperation at this stage may not be viable.

I should also add that I learned a lot about modern C++ features from your repository. Thank you! Feel free to close this issue, as I understand this is not an active development on your end.

**Comment by frozenca** [comment]
This project was originally planned as a general-purpose STL-like container, so I am not aiming for particular purpose optimized for DB. However, I'm very happy to hear that the development is being continued for useful purpose. Thank you!
