### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by svenbieg** [frozenca/BTree#3]
I've tried to make a comparison to my [Clusters](http://github.com/svenbieg/Clusters)-algorithm, but Your BTreeSet<int> needed about 30 seconds for 10.000 items. There were about 35.000 allocations for only 10.000 items!

**Comment by frozenca** [comment]
Did you try release build? Debug build tries full sanity check for *every* node for each insert, erase, join and split.
(Sanity check for a full tree is O(n), just 35000 allocations would never get close to even 30 milliseconds)

To turn off sanity check for all nodes in debug build, you can comment out these lines:

https://github.com/frozenca/BTree/blob/a6a514c4cc23b39636b17089e807701a40619f82/fc_btree.h#L349
https://github.com/frozenca/BTree/blob/a6a514c4cc23b39636b17089e807701a40619f82/fc_btree.h#L527-#L528

**Comment by frozenca** [comment]
I'll add a documentation for these sanity checks and turn off them for debug build.

These will be used for internal testing only.

**Comment by frozenca** [comment]
https://github.com/frozenca/BTree/commit/a9edf86cc0d58ec186d9c8d1cec0a3f30254d51b
https://github.com/frozenca/BTree/commit/adf3c3309f45a65010d767df674c232c12f5c00a

Turned off sanity checking for the entire tree. (But there are still a lot of ```assert``` in debug builds, so don't expect performance in debug build)

Please let me know if you still find issues in release build

**Comment by svenbieg** [comment]
It's a lot better now, but You should have a look at Clusters!

![btree_cls](https://user-images.githubusercontent.com/12587394/180625822-a6f91b4e-9993-475b-b064-c63d1f0185f5.jpg)

**Comment by frozenca** [comment]
1. What are your compiler version and optimization flags?
Generally it doesn't make sense to check performance without turning on maximum optimization level.

Inserting 100,000 ```std::int64_t``` in ```frozenca::DiskBTreeSet``` and ```std::set``` gives the following result in my machine: (repeated 50 times)

```
frozenca::DiskBTreeSet test
Time to insert 100000 elements:
Average : 18.5565ms,
Stdev   : 2.23727ms,
95%     : 22.9577ms,
99%     : 24.5757ms,
99.9%   : 24.5757ms,

std::set test
Time to insert 100000 elements:
Average : 25.1034ms,
Stdev   : 4.52327ms,
95%     : 36.5832ms,
99%     : 42.0014ms,
99.9%   : 42.0014ms,
```


3. Try a larger fanout, the default fanout (```t = 2```) is not very performant, for example:
```cpp
// fanout 16
frozenca::BTreeSet<int, 16> btree;
```

**Comment by svenbieg** [comment]
I have Visual Studio standard settings. If i try to set the fanout i get a compiler-error:

static_assert failed: 'Fanout customization for leaves is not allowed for disk B-trees'

But i don't have a disk B-tree?!

**Comment by frozenca** [comment]
Ugh, there was a mistake in adding that check. I will upload the fix soon.

But again, measuring performance is pointless without turning on compiler optimizations to the maximum.
For MSVC it is ```/Ox```. You can google it how to do it

**Comment by frozenca** [comment]
https://github.com/frozenca/BTree/commit/93cf63c4cabf29ea096b2ada1ed42ec706cafbf1

Disabled fanout customization for leaf nodes, now you can customize fanouts for non-disk B-Tree

**Comment by svenbieg** [comment]
I have set optimization to /Ox and insert 1'000'000 items now. Your B-tree seems to be a bit faster, but Clusters are much smaller.

![btree_cls](https://user-images.githubusercontent.com/12587394/180626291-829fec2e-71be-4a92-b6fe-c6dbafbedc82.jpg)

I did some testing with another btree-implementation, Your's seems to be better!

Maybe if You optimize Clusters, You get an even better result. I'm a hobby-programmer only.

**Comment by svenbieg** [comment]
I've been free to take-over some of Your ideas:

- I didn't know std::forward
- The template argument to prevent double string creation
- C++ for-each compatibility
- Iterator-traits

I had an issue with my uninitialized array, but i fixed it. I'm adding 1'000'000 strings backwards now, the worst case for Clusters:

![btree](https://user-images.githubusercontent.com/12587394/182047423-6bedae63-036b-43ae-9f64-f4dc422bf444.jpg)


I think Clusters is the better choice, but thank You very much for Your publication!
Maybe You like to do a C++20-implementation of Clusters, too?

Best regards,

Sven Bieg

**Comment by frozenca** [comment]
- Maybe You like to do a C++20-implementation of Clusters, too?
No

For benchmark, I can't read German. Is your implementation better for what? Memory footprint? Or runtime? Did you test the code in the release build with maximum compiler optimization? What was your test code? 

I didn't really tested std::string so far, so it still has a lot of room to optimize.

**Comment by svenbieg** [comment]
Yes, i've made a release-build with full optimization and Your B-Tree-implementation is very good!
My code is following:

```
int count=1'000'000;
CHAR str[16];
frozenca::BTreeMap<std::string, int, 16> fmap;
Clusters::map<std::string, int, uint32_t, 16> cmap;
for(int i=count-1; i>-1; i--)
	{
	sprintf_s(str, 16, "%i", i);
	fmap[str]=i;
	}
for(int i=count-1; i>-1; i--)
	{
	sprintf_s(str, 16, "%i", i);
	cmap.set(str, i);
	}
```
The benchmark shows that Clusters are almost as fast as B-Tree and are only about half the size. I've changed the language to english, i didn't mind.
Lookup takes less time with B-Tree, i can't imagine why.

I'm actually working on my web-server for Windows, Linux and ESP32.
The smaller memory-footprint is important on this small SoC, and custom allocators won't help there.
I already have my own memory-manager [esp32-heap](http://github.com/svenbieg/esp32-heap) based on Clusters.

You could do the implementation in a few days, i don't know what You are using Your B-Tree for.
Maybe You do a comparison by Yourself and change Your mind? I don't think maximum speed is that important.

**Comment by frozenca** [comment]
1. The factor that is important for someone is not equally important to everyone else, memory footprint is not my first optimization target (but of course it will be better to use smaller footprint). For B-Trees, Nodes have many other attributes like `size_`, `index_`, `height_`, etc, which enables fast join/split operations and order statistics lookups. (such as `kth()`, `order()`)

2. Using fanout 16 is very inefficient for B-Trees (I use 64 or 128)

3. `operator[]` is suboptimal, can you try `emplace(str, i)`

**Comment by svenbieg** [comment]
I changed fanout to 64 and use emplace()

```
frozenca::BTreeMap<std::string, int, 64> fmap;
for(int i=count-1; i>-1; i--)
	{
	sprintf_s(str, 16, "%i", i);
	fmap.emplace(str, i);
	}
```
operator[] is not subobtimal, same result:

![btree](https://user-images.githubusercontent.com/12587394/182047846-48d12a9b-4beb-47ed-beee-76bdf48031f5.jpg)

**Comment by svenbieg** [comment]
A fanout of 128 doesn't seem to be a good idea:

![btree](https://user-images.githubusercontent.com/12587394/182048222-f3c6948b-06fa-4a11-96d7-a5f6df224bd3.jpg)

**Comment by frozenca** [comment]
For memory footprint, could you remove this part and try again?

https://github.com/frozenca/BTree/blob/main/fc_btree.h#L199

(Not removing the entire line, I mean just to comment out `keys_.reserve(disk_max_nkeys); `)

**Comment by frozenca** [comment]
For non-pod types (like `std::string`, etc), I see there is a lot of room for improvement. I'm planning to change implementation to use `std::deque` soon

**Comment by svenbieg** [comment]
I'm sorry i don't understand much of Your C++-standard terms, but i've made Your test. I've commented out reservation and set the fanout back to 16.

```
Node() { /*keys_.reserve(disk_max_nkeys);*/ }
```

Here are the results, but now Clusters are smaller and faster:

fanout 16:

![btree](https://user-images.githubusercontent.com/12587394/182049106-f3c06a95-e5bc-4f72-9fa0-7f4a67d282ab.jpg)

fanout 64:

![btree1](https://user-images.githubusercontent.com/12587394/182049199-d13644e8-e267-49f6-8325-256dfaf8aa74.jpg)

Nobody knows Clusters, it's my own invention. The B-Tree-algorithm is 30 years old i think.

**Comment by svenbieg** [comment]
I'm using handles like Windows-Runtime, having a reference-count on each object. So i have comparable string-handles in my Clusters which are simple pointers.

**Comment by frozenca** [comment]
std::string was not my main concern so far, so it is currently under development.
The current implementation is suboptimal, so there will be improvements in the near future.

Did you tried benchmark with integer types (using SIMD) with the latest main branch?

**Comment by svenbieg** [comment]
Sorry, __builtin_ffs not found.

**Comment by svenbieg** [comment]
There is another issue with int64_t:

fc_btree.h(916,24): error C2672: 'operator __surrogate_func': no matching overloaded function found

**Comment by svenbieg** [comment]
Okay, B-Trees are much faster on integers without even using SIMD. I'm adding 10'000'000 integers now:

![btree](https://user-images.githubusercontent.com/12587394/182051317-28c54aa5-8b61-4c01-a377-b51a39568bad.jpg)

(fansize 64)

**Comment by frozenca** [comment]
B-Tree's true power comes from locality of keys, so only keys with trivial types (e.g. char, int, float, enum, pointers and their arrays, and classes consisting only of them or their arrays) can benefit B-Tree's true power.

For types like std::string, it is still usable, but probably will not the best choice
(When I use string-like key types, I store them as char[16], char[8], etc)

**Comment by svenbieg** [comment]
I think You only make a benefit of custom allocators, but i can see You are a professional.
If You would port my algorithm to Your STL-library, i'm sure You would get better results.
Please feel free to have Your own implementation under Apache and Boost-licence!

**Comment by frozenca** [comment]
custom allocators are only used for Disk B-Trees, regular ones use standard allocators (`std::allocator<Node>`)

**Comment by svenbieg** [comment]
This standard-allocators are custom allocators, invisible to my benchmark-system. In the Windows-kernel this is called PagedLookasideList and NPagedLookasideList.

**Comment by frozenca** [comment]
I just uploaded a commit to enable SIMD for MSVC, you can give it a try (by setting `FC_USE_SIMD` to 1)
In my machine it gave speedup about 20%

**Comment by svenbieg** [comment]
Exactly the same on my system, with and without SIMD.

B-Tree: 2.3s / Clusters: 4.35s

The benchmark above looks better for B-Tree, You must have changed something else.

**Comment by frozenca** [comment]
What was your test code?

**Comment by svenbieg** [comment]
Oops, i changed the fanout to 16.

```
frozenca::BTreeMap<int, int, 16> fmap;
Clusters::map<int, int, uint32_t, 16> cmap;
for(int i=count-1; i>-1; i--)
	{
	fmap.emplace(i, i);
	}
for(int i=count-1; i>-1; i--)
	{
	cmap.set(i, i);
	}
```

But SIMD didn't make any difference.

**Comment by frozenca** [comment]
Could you try larger fanouts? 64, 128, etc
Using SIMD is like doing process in 16 (or 8) units, so for fanout 16 it will not make a big difference

**Comment by svenbieg** [comment]
I tried 64 but i had the same result like in the benchmark above.

**Comment by frozenca** [comment]
I'm planning to implement two variants of B-Tree in the near future:

1. B-(B-minus) trees, specially designed for memory-scarce environments. (maybe you will be happy with this)
I am referring to these literature (they are good read, you may have a look)
https://en.algorithmica.org/hpc/data-structures/s-tree/
https://en.algorithmica.org/hpc/data-structures/b-tree/
This variant will not have pointers and other order statistics, so memory footprint will be much smaller,
and I except speedup will be about 30-50%: (but only trivially copyable keys can be used)

2. Lock-free B-trees, specially designed for very large scale database,
with highly concurrent access from multiple threads.
For machines with 16 CPU threads, I'm expecting speedup will be about x15


My B-Tree is general-purpose, it is not specialized for certain use case target.
so it will be a good baseline and compromise between them

**Comment by svenbieg** [comment]
I'm happy with Clusters!

B-Tree seems to be ideal for block-devices, but suboptimal for RAM-scenarios.

**Comment by svenbieg** [comment]
I think 2.) won't work. You can not have two threads in Your tree, because You don't know if one of it needs to change the root.
You could try to insert in the leaf only, without locking the root, and queue the change if not possible. Or simply queue the change ;-). You'd just need a low priority task doing changes.
Maybe You implement a higher class like BTreeMapMT with a lock and a queue, creating this task? You could return items in the queue immediatly and leave Your code as it is this way.

https://stackoverflow.com/questions/244316/reader-writer-locks-in-c

I can see two locks there!

For Your queue i can recommend You [Clusters](http://github.com/svenbieg/clusters).

There was a hint in Your readme, lock-free is impossible.

**Comment by frozenca** [comment]
there are a lot of smart people in the world and there are also actual papers and references:

http://www.cs.technion.ac.il/~erez/Papers/lfbtree-full.pdf
https://runshenzhu.github.io/618-final/
http://www.cs.umanitoba.ca/~hacamero/Research/BtreeTechrpt2011.pdf

**Comment by svenbieg** [comment]
Those people are crazy! The question is if this is necessary.
If i was You, i'd rename my classes with small letters and implement thread-safe classes with capital letters, maybe in .hpp-files. I have these classes for Clusters in my private code-space already, simply locking and forwarding to my public classes. I could make these public, but i'd need to publish Object and Handle then.
My web-server creates one task for each request, i need a locking-mechanism for that.

**Comment by frozenca** [comment]
_i'd rename my classes with small letters and implement thread-safe classes with capital letters, maybe in .hpp-files_
No

_I have this classes for Clusters in my private code-space already, simply locking and forwarding to my public classes._
lock-free B-trees seem to use a mechanism similar to internal load balancer and worker pool, I think I can isolate that mechanism using `if constexpr`

**Comment by svenbieg** [comment]
I'm sorry i don't understand. At stage 4 You still have to change the root. Changing without locking?

**Comment by frozenca** [comment]
I'm not your teacher, I can't answer everything.
Changing without locking is possible, we call that CAS operation

**Comment by svenbieg** [comment]
Like i said, You are a professional. I'm just a hobby-programmer, i do my own thing.
Thank You for the links, maybe i find something interesting for Clusters.

I'm wishing You success!

**Comment by svenbieg** [comment]
What about a new PalmTree class for big-data?

There is one difference in our code. I have a shared base-class for set and map, You are using a const expression is_set here.

Again, i'd use small letters, except for the lock-free PalmTree.

**Comment by frozenca** [comment]
No.

In general, you don't suggest to change other people's code style unless they asked you a review (this is different with a bug report).
Rewriting other's implementation is pointless.

**Comment by svenbieg** [comment]
This were just two tipps in a closed issue.
Having multiple files would improve readability.

Best regards,

Sven Bieg
