### ISSUE TITLE
Problem with find() and erase()

### ISSUE THREAD

**Issue by svenbieg** [frozenca/BTree#4]
I tried lookup and erasion:

`frozenca::BTreeMap<std::string, int> map;`
`map.find(str);`
`map.erase(str);`

With both functions i get this error:

fc_btree.h(876,15): error C2664: "const K &frozenca::Projection<const V &>::operator ()(const frozenca::BTreePair<K,int>&) noexcept const" : Konvertierung von Argument 1 von "const K" in "V" nicht möglich
fc_btree.h(876,17): message : Ursache: Konvertierung von "const K" in "const V" nicht möglich
fc_btree.h(876,18): message : Kein benutzerdefinierter Konvertierungsoperator verfügbar
fc_btree.h(56,15): message : Siehe Deklaration von "frozenca::Projection<const V &>::operator ()"

**Comment by frozenca** [comment]
I just added a fix, could you try again?

**Comment by svenbieg** [comment]
It's working now!
