### ISSUE TITLE
x64-compilation warning

### ISSUE THREAD

**Issue by svenbieg** [frozenca/BTree#5]
fc_btree.h(881,39): warning C4244: "Argument": Konvertierung von "__int64" in "frozenca::attr_t", möglicher Datenverlust

**Comment by svenbieg** [comment]
The line-number seems to be out of date. The warning comes from const_iterator_type search(const K &key).
You got auto i=std::distance(...) and return const_iterator_type(x, i).

**Comment by frozenca** [comment]
Already fixed in the latest master branch, pull the branch. There was a lot of improvement yesterday including significant performance gain
