### ISSUE TITLE
std::ranges don't work with integers

### ISSUE THREAD

**Issue by svenbieg** [frozenca/BTree#6]
I tried to create an integer-map.

```
frozenca::BTreeMap<int, int, 64> map;
map.emplace(0, 0);
```

fc_btree.h(916,24): error C2672: 'operator __surrogate_func': no matching overloaded function found

It comes from std::ranges::find_if_not()

**Comment by frozenca** [comment]
Should be fixed in eacef64

**Comment by svenbieg** [comment]
Compiling with zero errors!
